### PR TITLE
Fix for renderPath option #26

### PR DESCRIPTION
**Pull request by kuroyuki**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/serve-static/issues/26

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by zohar1000** [comment]
@kuroyuki  I stumbled on this bug and google search brought me to your commit.
I looked at the code and it looks like the line:
`const renderPath = options.rootPath;`
should be 
`const renderPath = options.renderPath;`
I checked and it worked fine with me.

Thanks, Zohar

**Comment by taosher** [comment]
need this fix very much. 

@kamilmysliwiec if u do not have time to review and merge prs in this repo, I can do some help. Because I  have read the code throughly and can be a collaborator.

**Comment by kamilmysliwiec** [comment]
If you just want to serve static files (not a SPA application), you shouldn't really use this package, but rather simply call:

> app.useStaticAssets(join(__dirname, '..', 'public'));

https://docs.nestjs.com/techniques/mvc

**Comment by Gehbrial** [comment]
> If you just want to serve static files (not a SPA application), you shouldn't really use this package, but rather simply call:
> 
> > app.useStaticAssets(join(__dirname, '..', 'public'));
> 
> https://docs.nestjs.com/techniques/mvc

If you want to serve static files, you shouldn't use the package called **serve-static**?!

**Comment by kamilmysliwiec** [comment]
> If you want to serve static files, you shouldn't use the package called serve-static?!

This package is primarily intended to serve SPA apps.

**Pull request closed without merging**
