### PR TITLE
fix(): `serveStaticOptions` is not correctly passed to fastify-static

### PR DESCRIPTION
**Pull request by geekdada**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/serve-static/issues/187

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by geekdada** [comment]
ping @kamilmysliwiec

**Comment by geekdada** [comment]
Hi @kamilmysliwiec , does anyone care to have a look on this, thanks!

**Comment by geekdada** [comment]
Ping @kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
Thanks!

**Pull request merged**
